version: "3.7"

services:
  tcs-front:
    image: lcbutch/tcs-front:${TAG}
    ports:
      - "80:80"

  tcs-service:
    image: lcbutch/tcs-service:${TAG}
    environment:
      - "DB:connectionString"

  tcs-db:
    build:
      context: .
      args:
        - ACCEPT_EULA=Y
        - SA_PASSWORD
    image: microsoft/mssql-server-linux
    expose:
      - "1443"
    volumes:
      - db-data:/var/opt/mssql

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

volumes:
  db-data:
