version: "3.7"

services:
  tcs-front:
    image: lcbutch/tcs-front:${TAG}
    ports:
      - "80:80"

  tcs-service:
    image: lcbutch/tcs-service:${TAG}
    ports:
      - "8080:80"
    environment:
      DB:connectionString: "Server=tcs-db;Database=tcs;User Id=SA;Password=Develop@90"
      AppSettings:Secret: SuperSecretkeyThatNooneWillEverknow
      ASPNETCORE_ENVIRONMENT: DEVELOPMENT

  tcs-db:
    image: microsoft/mssql-server-linux
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Develop@90
    expose:
      - "1443"
    volumes:
      - db-data:/var/opt/mssql

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

volumes:
  db-data:
